import {
  Bell,
  Boxes,
  Globe,
  Layers2,
  UserKey,
  Settings,
  UserStar,
  Container,
  LayoutGrid,
  CircleUser,
  Columns3Cog,
  FolderKanban,
  ShoppingCart,
  PackageCheck,
  MessageSquare,
  ChartNoAxesColumn,
  Mail,
} from "lucide-react";
import { createElement } from "react";
import { Permission } from "@/types/role-and-permissions";
import type { DashboardNavigationItem } from "@/types/dashboard-layout";

export const navigation = (
  permissions: Permission[],
): DashboardNavigationItem[] => [
  {
    label: "sidebar.navigation.overview",
    type: "label",
    enabled: true,
  },
  {
    label: "sidebar.navigation.dashboard",
    href: "/",
    type: "link",
    icon: createElement(LayoutGrid, { className: "h-4 w-4" }),
    enabled: true,
  },
  {
    label: "sidebar.navigation.catalog",
    type: "label",
    enabled: true,
  },
  {
    label: "sidebar.navigation.products",
    href: "/products",
    type: "link",
    icon: createElement(FolderKanban, { className: "h-4 w-4" }),
    enabled: permissions.includes("catalog.view"),
  },
  {
    label: "sidebar.navigation.categories",
    href: "/categories",
    type: "link",
    icon: createElement(Layers2, { className: "h-4 w-4" }),
    enabled: permissions.includes("catalog.view"),
  },
  {
    label: "sidebar.navigation.customBuilder",
    href: "/custom-builder",
    type: "link",
    icon: createElement(Columns3Cog, { className: "h-4 w-4" }),
    enabled: permissions.includes("catalog.view"),
  },
  {
    label: "sidebar.navigation.sales",
    type: "label",
    enabled: true,
  },
  {
    label: "sidebar.navigation.orders",
    href: "/orders",
    type: "link",
    icon: createElement(ShoppingCart, { className: "h-4 w-4" }),
    enabled: permissions.includes("orders.view"),
  },
  {
    label: "sidebar.navigation.customers",
    href: "/customers",
    type: "link",
    icon: createElement(CircleUser, { className: "h-4 w-4" }),
    enabled: permissions.includes("users.view"),
  },
  {
    label: "sidebar.navigation.reviews",
    href: "/reviews",
    type: "link",
    icon: createElement(MessageSquare, { className: "h-4 w-4" }),
    enabled: permissions.includes("reviews.view"),
  },
  {
    label: "sidebar.navigation.reports",
    href: "/reports",
    type: "link",
    icon: createElement(ChartNoAxesColumn, { className: "h-4 w-4" }),
    enabled: true,
  },
  {
    label: "sidebar.navigation.marketing",
    type: "label",
    enabled: true,
  },
  {
    label: "sidebar.navigation.promoCodes",
    href: "/promo-codes",
    type: "link",
    icon: createElement(Container, { className: "h-4 w-4" }),
    enabled: permissions.includes("coupons.view"),
  },
  {
    label: "sidebar.navigation.occasionsCollections",
    href: "/occasions",
    type: "link",
    icon: createElement(Boxes, { className: "h-4 w-4" }),
    enabled: permissions.includes("catalog.view"),
  },
  {
    label: "sidebar.navigation.settings",
    type: "label",
    enabled: true,
  },
  {
    label: "sidebar.navigation.countriesCities",
    href: "/countries-cities",
    type: "link",
    icon: createElement(Globe, { className: "h-4 w-4" }),
    enabled: true,
  },
  {
    label: "sidebar.navigation.storeSettings",
    href: "/store-settings",
    type: "link",
    icon: createElement(Settings, { className: "h-4 w-4" }),
    enabled: permissions.includes("settings.view"),
  },
  {
    label: "sidebar.navigation.messages",
    href: "/messages",
    type: "link",
    icon: createElement(Mail, { className: "h-4 w-4" }),
    enabled: permissions.includes("contact.view"),
  },
  {
    label: "sidebar.navigation.deliveryPickup",
    href: "/delivery-pickup",
    type: "link",
    icon: createElement(PackageCheck, { className: "h-4 w-4" }),
    enabled: true,
  },
  {
    label: "sidebar.navigation.notifications",
    href: "/notifications",
    type: "link",
    icon: createElement(Bell, { className: "h-4 w-4" }),
    enabled: permissions.includes("notifications.view"),
  },
  {
    label: "sidebar.navigation.rolesAndPermissions",
    href: "/roles-and-permissions",
    type: "link",
    icon: createElement(UserKey, { className: "h-4 w-4" }),
    enabled: permissions.includes("roles.view"),
  },
  {
    label: "sidebar.navigation.adminAccount",
    href: "/admin-account",
    type: "link",
    icon: createElement(UserStar, { className: "h-4 w-4" }),
    enabled: true,
  },
];
