import { twMerge } from "tailwind-merge";
import { clsx, type ClassValue } from "clsx";
import { Product, ProductFormValues } from "@/types/products";
import { initialFlower, initialVariant } from "@/constants/products";

/**
 * Utility function to merge class names using clsx and tailwind-merge.
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/**
 * Normalizes a hex color string to a standard 6-character format.
 */
export const normalizeHexColor = (value: string) => {
  const trimmed = value.trim().toLowerCase();
  if (!trimmed) return null;
  const withHash = trimmed.startsWith("#") ? trimmed : `#${trimmed}`;
  if (/^#[0-9a-f]{3}$/.test(withHash)) {
    return `#${withHash[1]}${withHash[1]}${withHash[2]}${withHash[2]}${withHash[3]}${withHash[3]}`;
  }
  if (/^#[0-9a-f]{6}$/.test(withHash)) {
    return withHash;
  }
  return null;
};

/**
 * Creates a URL-friendly slug from a given string.
 * The slug is generated by converting the string to lowercase, trimming whitespace,
 * removing special characters, and replacing spaces with hyphens.
 */
export const createSlug = (value: string) =>
  value
    .toLowerCase()
    .trim()
    .replace(/["'’]/g, "")
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");

/**
 * Formats a date string or Date object into a human-readable format (e.g., "Jan 01, 2024").
 */
export const formatDate = (date: string | Date) =>
  new Date(date).toLocaleDateString("en-US", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

/**
 * Get Default Values for Product Form
 * This function returns the default values for a product form,
 * either from an existing product or as empty values for a new product.
 */
export function getProductDefaultValues(product?: Product): ProductFormValues {
  return {
    name: product?.name || { en: "", ar: "" },
    description: product?.description || { en: "", ar: "" },
    category_id: product?.category_id || 0,
    occasion_ids: product?.occasion_ids || [],
    tags: product?.tags || [],
    sku: product?.sku || "",
    status: product?.status || "published",
    images: product?.images.map((image) => image.url) || [],
    is_new: product?.is_new || false,
    variants: product?.variants.map((variant) => ({
      id: variant.id,
      sku: variant.sku,
      size: variant.size,
      price: variant.price,
      stock: variant.stock,
      compare_at_price: variant.compare_at_price,
      color_hex: variant.color_hex,
      in_stock: variant.in_stock,
      is_on_sale: variant.is_on_sale,
      recipe: variant.recipe.length ? variant.recipe : [initialFlower],
    })) || [initialVariant],
  };
}
