import { twMerge } from "tailwind-merge";
import { clsx, type ClassValue } from "clsx";
import { Product, ProductFormValues } from "@/types/products";
import { initialFlower, initialVariant } from "@/constants/products";

/**
 * Utility function to merge class names using clsx and tailwind-merge.
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/**
 * Normalizes a hex color string to a standard 6-character format.
 */
export const normalizeHexColor = (value: string) => {
  const trimmed = value.trim().toLowerCase();
  if (!trimmed) return null;
  const withHash = trimmed.startsWith("#") ? trimmed : `#${trimmed}`;
  if (/^#[0-9a-f]{3}$/.test(withHash)) {
    return `#${withHash[1]}${withHash[1]}${withHash[2]}${withHash[2]}${withHash[3]}${withHash[3]}`;
  }
  if (/^#[0-9a-f]{6}$/.test(withHash)) {
    return withHash;
  }
  return null;
};

/**
 * Creates a URL-friendly slug from a given string.
 * The slug is generated by converting the string to lowercase, trimming whitespace,
 * removing special characters, and replacing spaces with hyphens.
 */
export const createSlug = (value: string) =>
  value
    .toLowerCase()
    .trim()
    .replace(/["'’]/g, "")
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");

/**
 * Formats a date string or Date object into a human-readable format (e.g., "Jan 01, 2024").
 */
export const formatDate = (date: string | Date): string => {
  const value = new Date(date);

  if (Number.isNaN(value.getTime())) return "";

  const today = new Date();
  const yesterday = new Date(today);
  yesterday.setDate(today.getDate() - 1);

  const isSameDay = (a: Date, b: Date) =>
    a.getFullYear() === b.getFullYear() &&
    a.getMonth() === b.getMonth() &&
    a.getDate() === b.getDate();

  const time = value.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  });

  const day = isSameDay(value, today)
    ? "today"
    : isSameDay(value, yesterday)
      ? "yesterday"
      : value.toLocaleDateString("en-US", {
          day: "2-digit",
          month: "short",
          year: "numeric",
        });

  return `${day}, ${time}`;
};

/**
 * Get Default Values for Product Form
 * This function returns the default values for a product form,
 * either from an existing product or as empty values for a new product.
 */
export function getProductDefaultValues(
  type: "default" | "addon",
  product?: Product,
): ProductFormValues {
  return {
    name: product?.name || { en: "", ar: "" },
    description: product?.description || { en: "", ar: "" },
    eta_text: product?.eta_text || { en: "", ar: "" },
    category_id: product?.category_id || 0,
    occasion_ids: product?.occasion_ids || [],
    sku: product?.sku || "",
    status: product?.status || "published",
    is_purchasable: true,
    show_in_builder: false,
    images: product?.images.map((image) => image.url) || [],
    is_new: product?.is_new || false,
    variants: product?.variants.map((variant) => ({
      id: variant.id || undefined,
      sku: variant.sku || "",
      size: variant.size || "",
      price: variant.price || 0,
      compare_at_price: variant.compare_at_price || undefined,
      discount: variant.compare_at_price
        ? ((variant.compare_at_price - variant.price) /
            variant.compare_at_price) *
          100
        : undefined,
      recipe: variant.recipe.length
        ? variant.recipe
        : type === "default"
          ? [initialFlower]
          : [],
    })) || [
      { ...initialVariant, recipe: type === "default" ? [initialFlower] : [] },
    ],
  };
}

/**
 * Canonical public origin for building absolute redirect URLs, if configured.
 * Intentionally does NOT fall back to a request-derived origin: behind a
 * reverse proxy the Host header isn't always forwarded, so that can resolve
 * to an internal/localhost address in production instead of the real domain.
 */
export function getAppUrl() {
  return process.env.APP_URL || null;
}

/**
 * Extract CSV data from a string into an array of objects.
 */
export function parseCsv(csvString: string, name: string) {
  const blob = new Blob([csvString], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${name}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
