"use client";

import {
  Category,
  CategoryFormValues,
  categorySchema,
  CategoryType,
} from "@/types/categories";
import { toast } from "sonner";
import Input from "../form/input";
import Switch from "../form/switch";
import Footer from "../form/footer";
import Header from "../form/header";
import { Button } from "../ui/button";
import { Flower2 } from "lucide-react";
import { useEffect, useRef } from "react";
import AddButton from "../form/add-button";
import { Separator } from "../ui/separator";
import { cn, createSlug } from "@/lib/utils";
import { useRouter } from "@/i18n/navigation";
import { Card, CardContent } from "../ui/card";
import SectionLabel from "../form/section-label";
import { zodResolver } from "@hookform/resolvers/zod";
import { availableLocales } from "@/constants/shared";
import { useLocale, useTranslations } from "next-intl";
import { useFormLocale } from "@/hooks/use-form-locale";
import { postCategoryAction } from "@/lib/categories";
import LocaleFormSwitcher from "../reusable/locale-form-switcher";
import { useForm, useWatch, SubmitHandler } from "react-hook-form";
import SingleFormImageUploader from "../form/single-image-uploader";
import { Sheet, SheetClose, SheetContent, SheetTrigger } from "../ui/sheet";

// Generate default values for the form based on the provided category or return empty values if no category is provided
function generateDefaultValues(
  sortOrder: number,
  type: CategoryType,
  category?: Category,
): CategoryFormValues {
  return {
    name: category?.name || { en: "", ar: "" },
    slug: category?.slug || "",
    type: type,
    is_visible: category?.is_visible ?? false,
    icon: category?.icon_url || "",
    banner: category?.banner_url || "",
    sort_order: category?.sort_order || sortOrder || 0,
  };
}

type CreateEditProps = {
  category?: Category;
  trigger?: React.ReactNode;
  totalCreatedItems: number;
  type: CategoryType;
};

export default function CreateEdit({
  category,
  trigger,
  totalCreatedItems,
  type,
}: CreateEditProps) {
  const router = useRouter();
  const locale = useLocale();
  const t = useTranslations("Categories");
  const tCommon = useTranslations("Common");
  const form = useRef<HTMLFormElement>(null);
  const isSlugManuallyEdited = useRef(Boolean(category?.slug));
  const lastAutoGeneratedSlug = useRef(category?.slug || "");
  const closeBtn = useRef<HTMLButtonElement>(null);
  const { activeLocale, changeLocale, dir, isArabic, tLive } =
    useFormLocale("Categories");

  const {
    control,
    register,
    reset,
    setValue,
    setError,
    getValues,
    trigger: triggerValidation,
    handleSubmit,
    formState: { errors, isSubmitting, isSubmitted },
  } = useForm<CategoryFormValues>({
    defaultValues: generateDefaultValues(totalCreatedItems, type, category),
    resolver: zodResolver(categorySchema((key) => tLive(key as never))),
  });

  useEffect(() => {
    if (isSubmitted) {
      void triggerValidation();
    }
  }, [isSubmitted, triggerValidation, activeLocale]);

  // Watch the name and slug fields to handle automatic slug generation and manual edits
  const watchName = useWatch({ control, name: "name" });
  const watchSlug = useWatch({ control, name: "slug" });

  // Effect to automatically generate slug based on the name field when it changes, unless the slug has been manually edited
  useEffect(() => {
    if (isSlugManuallyEdited.current) return;

    const sourceName = watchName?.en?.trim() || "";
    const generatedSlug = createSlug(sourceName);
    lastAutoGeneratedSlug.current = generatedSlug;

    if (generatedSlug === getValues("slug")) return;

    setValue("slug", generatedSlug, {
      shouldDirty: Boolean(generatedSlug),
      shouldValidate: true,
    });
  }, [activeLocale, getValues, setValue, watchName]);

  // Effect to detect if the slug has been manually edited by the user
  useEffect(() => {
    if (
      !isSlugManuallyEdited.current &&
      typeof watchSlug === "string" &&
      watchSlug !== lastAutoGeneratedSlug.current
    ) {
      isSlugManuallyEdited.current = true;
    }
  }, [watchSlug]);

  // Handle form submission by calling the postCategoryAction function and displaying appropriate success or error messages
  const onSubmit: SubmitHandler<CategoryFormValues> = async (data) => {
    const failedMessage = category
      ? tCommon("UpdateFailed")
      : tCommon("CreationFailed");

    let result: Awaited<ReturnType<typeof postCategoryAction>>;

    try {
      result = await postCategoryAction(data, category?.id);
    } catch (error) {
      // The request itself failed (offline, upload too large for the server)
      console.error("Error submitting category:", error);
      toast.error(failedMessage);
      return;
    }

    if (result.success) {
      toast.success(result.message);
      router.refresh();
      closeBtn.current?.click();
      return;
    }

    if (result.errors) {
      Object.entries(result.errors).forEach(([field, message]) => {
        toast.error(message);
        setError(field as keyof CategoryFormValues, {
          type: "server",
          message,
        });
      });

      return;
    }

    toast.error(result.message ?? failedMessage);
  };

  return (
    <Sheet
      onOpenChange={(open) => {
        if (!open) return;

        // Start from the latest saved values every time the sheet opens
        isSlugManuallyEdited.current = Boolean(category?.slug);
        lastAutoGeneratedSlug.current = category?.slug || "";
        reset(generateDefaultValues(totalCreatedItems, type, category));
      }}
    >
      {trigger ? (
        <SheetTrigger asChild>{trigger}</SheetTrigger>
      ) : (
        <AddButton
          label={type === "bouquet" ? t("AddCategory") : t("AddAddOnsCategory")}
        />
      )}

      <SheetContent
        showCloseButton={false}
        className="flex h-full flex-col sm:max-w-2xl"
        side={locale === "ar" ? "left" : "right"}
      >
        <SheetClose asChild>
          <Button ref={closeBtn} className="hidden"></Button>
        </SheetClose>

        <Header
          title={
            category
              ? type === "bouquet"
                ? t("EditCategory")
                : t("EditAddOnsCategory")
              : type === "bouquet"
                ? t("AddCategory")
                : t("AddAddOnsCategory")
          }
          description={
            type === "bouquet"
              ? t("CreateCategoryDescription")
              : t("CreateAddOnsCategoryDescription")
          }
        />

        <LocaleFormSwitcher
          locale={activeLocale}
          onChange={(locale) => {
            changeLocale(locale);
          }}
        />

        <div
          className={cn(`flex-1 overflow-auto px-4 pb-6 pt-2`, {
            "font-cairo": isArabic,
            "font-inter": !isArabic,
          })}
          dir={dir}
        >
          <form
            ref={form}
            onSubmit={(e) => {
              if (isSubmitting) {
                e.preventDefault();
                return;
              }

              void handleSubmit(onSubmit, (errors) => {
                // Check if current locale is English and there are Arabic field errors
                if (activeLocale === "en") {
                  const hasArErrors = errors.name?.ar;
                  if (hasArErrors) {
                    changeLocale("ar");
                    return;
                  }
                }

                // Check if current locale is Arabic and there are English field errors
                if (activeLocale === "ar") {
                  const hasEnErrors = errors.name?.en;
                  if (hasEnErrors) {
                    changeLocale("en");
                    return;
                  }
                }
              })(e);
            }}
            className="space-y-6 relative"
          >
            <Card>
              <CardContent className="flex items-center gap-2">
                <div className="bg-[#f4c2c233] p-2.5 rounded-lg">
                  <Flower2 className="size-5 text-[#b88686]" />
                </div>
                <div>
                  <p className="font-semibold text-sm">
                    {watchName?.[activeLocale] || tLive("Placeholder")}
                  </p>
                  <p className="text-muted-foreground text-xs mt-1">
                    /{watchSlug || tLive("Placeholder")}
                  </p>
                </div>
              </CardContent>
            </Card>

            <Separator className="bg-border" />
            <SectionLabel>{tLive("Details")}</SectionLabel>
            {availableLocales.map((lang) => (
              <Input<CategoryFormValues>
                key={lang}
                label={tLive("CategoryName")}
                placeholder={tLive("EnterCategoryName")}
                name={`name.${lang}`}
                type="text"
                register={register}
                errors={errors}
                required
                className={`${activeLocale === lang ? "" : "hidden"}`}
              />
            ))}

            <Input<CategoryFormValues>
              label={tLive("Slug")}
              placeholder={tLive("EnterSlug")}
              name="slug"
              type="text"
              register={register}
              errors={errors}
              required
              prefix="/"
              description={tLive("SlugHint")}
            />

            <SingleFormImageUploader
              control={control}
              name="icon"
              label={tLive("Icon")}
              accept=".svg"
              required
            />

            <SingleFormImageUploader
              control={control}
              name="banner"
              label={tLive("Banner")}
              required
            />

            <Separator className="bg-border" />
            <SectionLabel>{tLive("Visibility")}</SectionLabel>
            <Switch<CategoryFormValues>
              name="is_visible"
              control={control}
              label={tLive("VisibilityLabel")}
              description={tLive("VisibilityDescription")}
            />
          </form>
        </div>
        <Footer form={form} loading={isSubmitting} />
      </SheetContent>
    </Sheet>
  );
}
