"use client";

import {
  Category,
  CategoryFormValues,
  categorySchema,
  CategoryType,
} from "@/types/categories";
import { toast } from "sonner";
import Input from "../form/input";
import Switch from "../form/switch";
import Footer from "../form/footer";
import Header from "../form/header";
import { Button } from "../ui/button";
import { FieldError } from "../ui/field";
import { useEffect, useRef } from "react";
import AddButton from "../form/add-button";
import { Separator } from "../ui/separator";
import { cn, createSlug } from "@/lib/utils";
import { Check, Flower2 } from "lucide-react";
import Select from "@/components/form/select";
import { Card, CardContent } from "../ui/card";
import SectionLabel from "../form/section-label";
import { zodResolver } from "@hookform/resolvers/zod";
import { availableLocales } from "@/constants/shared";
import { useLocale, useTranslations } from "next-intl";
import { useFormLocale } from "@/hooks/use-form-locale";
import { postCategoryAction } from "@/lib/categories-actions";
import { categoryTypes, colors } from "@/constants/categories";
import LocaleFormSwitcher from "../reusable/locale-form-switcher";
import SingleFormImageUploader from "../form/single-image-uploader";
import { Sheet, SheetClose, SheetContent, SheetTrigger } from "../ui/sheet";
import { Controller, useForm, useWatch, SubmitHandler } from "react-hook-form";

// Generate default values for the form based on the provided category or return empty values if no category is provided
function generateDefaultValues(
  sortOrder: number,
  type: CategoryType,
  category?: Category,
): CategoryFormValues {
  return {
    name: category?.name || { en: "", ar: "" },
    slug: category?.slug || "",
    type: category?.type || type,
    color: category?.color || "",
    is_visible: category?.is_visible ?? false,
    icon: category?.icon_url || "",
    banner: category?.banner_url || "",
    sort_order: category?.sort_order || sortOrder || 0,
  };
}

// Get a list of colors, including the category's color if it's not already in the predefined list
function getListOfColors(color?: string): string[] {
  return [...colors, ...(color && !colors.includes(color) ? [color] : [])];
}

type CreateEditProps = {
  category?: Category;
  trigger?: React.ReactNode;
  totalCreatedItems: number;
  type: CategoryType;
};

export default function CreateEdit({
  category,
  trigger,
  totalCreatedItems,
  type,
}: CreateEditProps) {
  const locale = useLocale();
  const t = useTranslations("Categories");
  const tCommon = useTranslations("Common");
  const form = useRef<HTMLFormElement>(null);
  const isSlugManuallyEdited = useRef(Boolean(category?.slug));
  const lastAutoGeneratedSlug = useRef(category?.slug || "");
  const closeBtn = useRef<HTMLButtonElement>(null);
  const { activeLocale, changeLocale, dir, isArabic, tLive } =
    useFormLocale("Categories");

  const {
    control,
    register,
    setValue,
    setError,
    getValues,
    clearErrors,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<CategoryFormValues>({
    defaultValues: generateDefaultValues(totalCreatedItems, type, category),
    resolver: zodResolver(categorySchema((key) => tLive(key as never))),
  });

  // Watch the name and slug fields to handle automatic slug generation and manual edits
  const watchName = useWatch({ control, name: "name" });
  const watchSlug = useWatch({ control, name: "slug" });
  const watchColor = useWatch({ control, name: "color" });

  // Effect to automatically generate slug based on the name field when it changes, unless the slug has been manually edited
  useEffect(() => {
    if (isSlugManuallyEdited.current) return;

    const sourceName = watchName?.en?.trim() || "";
    const generatedSlug = createSlug(sourceName);
    lastAutoGeneratedSlug.current = generatedSlug;

    if (generatedSlug === getValues("slug")) return;

    setValue("slug", generatedSlug, {
      shouldDirty: Boolean(generatedSlug),
      shouldValidate: true,
    });
  }, [activeLocale, getValues, setValue, watchName]);

  // Effect to detect if the slug has been manually edited by the user
  useEffect(() => {
    if (
      !isSlugManuallyEdited.current &&
      typeof watchSlug === "string" &&
      watchSlug !== lastAutoGeneratedSlug.current
    ) {
      isSlugManuallyEdited.current = true;
    }
  }, [watchSlug]);

  // Handle form submission by calling the postCategoryAction function and displaying appropriate success or error messages
  const onSubmit: SubmitHandler<CategoryFormValues> = async (data) => {
    const result = await postCategoryAction(data, category?.id);

    if (result.success) {
      toast.success(
        category
          ? tCommon("UpdatedSuccessfully")
          : tCommon("CreatedSuccessfully"),
      );
      form.current?.reset();
      closeBtn.current?.click();
      return;
    }

    if (result.errors) {
      Object.entries(result.errors).forEach(([field, message]) => {
        toast.error(message);
        setError(field as keyof CategoryFormValues, {
          type: "server",
          message,
        });
      });

      return;
    }

    toast.error(category ? tCommon("CreationFailed") : tCommon("UpdateFailed"));
  };

  return (
    <Sheet>
      {trigger ? (
        <SheetTrigger asChild>{trigger}</SheetTrigger>
      ) : (
        <AddButton
          label={type === "default" ? t("AddCategory") : t("AddAddOnsCategory")}
        />
      )}

      <SheetContent
        showCloseButton={false}
        className="flex h-full flex-col sm:max-w-2xl"
        side={locale === "ar" ? "left" : "right"}
        onInteractOutside={(event) => event.preventDefault()}
      >
        <SheetClose asChild>
          <Button ref={closeBtn} className="hidden"></Button>
        </SheetClose>

        <Header
          title={type === "default" ? t("AddCategory") : t("AddAddOnsCategory")}
          description={
            type === "default"
              ? t("CreateCategoryDescription")
              : t("CreateAddOnsCategoryDescription")
          }
        />

        <LocaleFormSwitcher
          locale={activeLocale}
          onChange={(locale) => {
            changeLocale(locale);
            clearErrors();
          }}
        />

        <div
          className={cn(`flex-1 overflow-auto px-4 pb-6 pt-2`, {
            "font-cairo": isArabic,
            "font-inter": !isArabic,
          })}
          dir={dir}
        >
          <form
            ref={form}
            onSubmit={(e) => {
              void handleSubmit(onSubmit)(e);
            }}
            className="space-y-6 relative"
          >
            <Card>
              <CardContent className="flex items-center gap-2">
                <div className="bg-[#f4c2c233] p-2.5 rounded-lg">
                  <Flower2 className="size-5 text-[#b88686]" />
                </div>
                <div>
                  <p className="font-semibold text-sm">
                    {watchName?.[activeLocale] || tLive("Placeholder")}
                  </p>
                  <p className="text-muted-foreground text-xs mt-1">
                    /{watchSlug || tLive("Placeholder")}
                  </p>
                </div>
              </CardContent>
            </Card>

            <Separator className="bg-border" />
            <SectionLabel>{tLive("Details")}</SectionLabel>
            {availableLocales.map((lang) => (
              <Input<CategoryFormValues>
                key={lang}
                label={tLive("CategoryName")}
                placeholder={tLive("EnterCategoryName")}
                name={`name.${lang}`}
                type="text"
                register={register}
                errors={errors}
                required
                className={`${activeLocale === lang ? "" : "hidden"}`}
              />
            ))}

            <Input<CategoryFormValues>
              label={tLive("Slug")}
              placeholder={tLive("EnterSlug")}
              name="slug"
              type="text"
              register={register}
              errors={errors}
              required
              prefix="/"
              description={tLive("SlugHint")}
            />

            <Select<CategoryFormValues>
              control={control}
              name="type"
              label={tLive("Type")}
              options={categoryTypes((key) => tLive(key as never))}
              required
              placeholder={tLive("SelectType")}
              dir={dir}
              disabled
            />

            <SingleFormImageUploader
              control={control}
              name="icon"
              label={tLive("Icon")}
              accept=".svg"
              required
            />

            <SingleFormImageUploader
              control={control}
              name="banner"
              label={tLive("Banner")}
              required
            />

            <Separator className="bg-border" />
            <SectionLabel>{tLive("Color")}</SectionLabel>
            <Controller
              name="color"
              control={control}
              render={({ field }) => {
                const selectedColors = field.value ?? "";

                return (
                  <div className="space-y-1.5">
                    <div className="flex flex-wrap gap-2">
                      {getListOfColors(category?.color || watchColor).map(
                        (color) => {
                          const isSelected = selectedColors === color;

                          return (
                            <Button
                              key={color}
                              type="button"
                              variant="outline"
                              style={{ backgroundColor: color }}
                              className={cn(
                                "h-8 w-8 rounded-full border border-border",
                                { "border-2 border-primary": isSelected },
                              )}
                              onClick={() => {
                                const nextColors = isSelected ? "" : color;
                                field.onChange(nextColors);
                              }}
                            >
                              {isSelected && <Check />}
                            </Button>
                          );
                        },
                      )}

                      <div className="relative h-8 w-8">
                        <Button
                          variant="outline"
                          className="w-8 h-8 rounded-full border-2 border-dashed bg-white cursor-pointer"
                        ></Button>
                        <input
                          type="color"
                          className="absolute inset-0 h-full w-full cursor-pointer opacity-0"
                          onChange={(event) => {
                            field.onChange(event.target.value);
                          }}
                        />
                      </div>
                    </div>

                    <FieldError errors={[errors.color]} />
                  </div>
                );
              }}
            />

            <Separator className="bg-border" />
            <SectionLabel>{tLive("Visibility")}</SectionLabel>
            <Switch<CategoryFormValues>
              name="is_visible"
              control={control}
              label={tLive("VisibilityLabel")}
              description={tLive("VisibilityDescription")}
            />
          </form>
        </div>
        <Footer form={form} loading={isSubmitting} />
      </SheetContent>
    </Sheet>
  );
}
