"use client";

import {
  Occasion,
  occasionCollectionSchema,
  OccasionFormValues,
} from "@/types/occasions";
import { toast } from "sonner";
import Input from "../form/input";
import Footer from "../form/footer";
import Header from "../form/header";
import Switch from "../form/switch";
import { Button } from "../ui/button";
import { FieldError } from "../ui/field";
import { useEffect, useRef } from "react";
import AddButton from "../form/add-button";
import { Separator } from "../ui/separator";
import { cn, createSlug } from "@/lib/utils";
import { Check, Flower2 } from "lucide-react";
import { Card, CardContent } from "../ui/card";
import { colors } from "@/constants/occasions";
import SectionLabel from "../form/section-label";
import NormalFormRichText from "../form/rich-text";
import { zodResolver } from "@hookform/resolvers/zod";
import { availableLocales } from "@/constants/shared";
import { useLocale, useTranslations } from "next-intl";
import { useFormLocale } from "@/hooks/use-form-locale";
import { postOccasionAction } from "@/lib/occasion-actions";
import LocaleFormSwitcher from "../reusable/locale-form-switcher";
import SingleFormImageUploader from "../form/single-image-uploader";
import { Sheet, SheetClose, SheetContent, SheetTrigger } from "../ui/sheet";
import { Controller, SubmitHandler, useForm, useWatch } from "react-hook-form";

// Get default values for the form based on the occasion collection data
function getDefaultValues(sortOrder: number, occasion?: Occasion) {
  return {
    name: occasion?.name_translations || { en: "", ar: "" },
    description: occasion?.description_translations || { en: "", ar: "" },
    slug: occasion?.slug || "",
    is_visible: occasion?.is_visible ?? true,
    type: "bouquet",
    color: occasion?.color || "",
    sort_order: occasion?.sort_order || sortOrder || 0,
    banner: occasion?.banner_url || "",
    starts_at: occasion?.starts_at?.split("T")[0] || "",
    ends_at: occasion?.ends_at?.split("T")[0] || "",
  };
}

// Get a list of colors, including the occasion's color if it's not already in the predefined list
function getListOfColors(color?: string): string[] {
  return [...colors, ...(color && !colors.includes(color) ? [color] : [])];
}

export default function CreateEdit({
  occasion,
  trigger,
  totalOccasionItems,
}: {
  occasion?: Occasion;
  trigger?: React.ReactNode;
  totalOccasionItems: number;
}) {
  const locale = useLocale();
  const t = useTranslations("Occasions");
  const tCommon = useTranslations("Common");
  const form = useRef<HTMLFormElement>(null);
  const closeBtn = useRef<HTMLButtonElement>(null);
  const isSlugManuallyEdited = useRef(Boolean(occasion?.slug));
  const lastAutoGeneratedSlug = useRef(occasion?.slug || "");
  const { tLive, changeLocale, activeLocale, dir, isArabic } =
    useFormLocale("Occasions");

  const {
    control,
    register,
    setValue,
    setError,
    getValues,
    clearErrors,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<OccasionFormValues>({
    defaultValues: getDefaultValues(totalOccasionItems, occasion),
    resolver: zodResolver(
      occasionCollectionSchema((key) => tLive(key as never)),
    ),
  });

  // Watch the color, name, and slug fields for changes
  const watchColor = useWatch({ control, name: "color" });
  const watchName = useWatch({ control, name: "name" });
  const watchSlug = useWatch({ control, name: "slug" });

  // Effect to automatically generate slug based on the name field when it changes, unless the slug has been manually edited
  useEffect(() => {
    if (isSlugManuallyEdited.current) return;

    const sourceName = watchName?.en?.trim() || "";
    const generatedSlug = createSlug(sourceName);
    lastAutoGeneratedSlug.current = generatedSlug;

    if (generatedSlug === getValues("slug")) return;

    setValue("slug", generatedSlug, {
      shouldDirty: Boolean(generatedSlug),
      shouldValidate: true,
    });
  }, [activeLocale, getValues, setValue, watchName]);

  // Effect to detect if the slug has been manually edited by the user
  useEffect(() => {
    if (
      !isSlugManuallyEdited.current &&
      typeof watchSlug === "string" &&
      watchSlug !== lastAutoGeneratedSlug.current
    ) {
      isSlugManuallyEdited.current = true;
    }
  }, [watchSlug]);

  const onSubmit: SubmitHandler<OccasionFormValues> = async (data) => {
    const result = await postOccasionAction(data, occasion?.id);

    if (result.success) {
      toast.success(
        occasion
          ? tCommon("UpdatedSuccessfully")
          : tCommon("CreatedSuccessfully"),
      );
      form.current?.reset();
      closeBtn.current?.click();
      return;
    }

    if (result.errors) {
      Object.entries(result.errors).forEach(([field, message]) => {
        toast.error(message);
        setError(field as keyof OccasionFormValues, {
          type: "server",
          message,
        });
      });

      return;
    }

    toast.error(occasion ? tCommon("CreationFailed") : tCommon("UpdateFailed"));
  };

  return (
    <Sheet>
      {trigger ? (
        <SheetTrigger asChild>{trigger}</SheetTrigger>
      ) : (
        <AddButton label={t("Labels.AddOccasionCollection")} />
      )}

      <SheetContent
        showCloseButton={false}
        className="flex h-full flex-col sm:max-w-2xl"
        side={locale === "ar" ? "left" : "right"}
        onInteractOutside={(event) => event.preventDefault()}
      >
        <SheetClose asChild>
          <Button ref={closeBtn} className="hidden"></Button>
        </SheetClose>

        <Header
          title={
            occasion
              ? t("Labels.EditOccasionCollection")
              : t("Labels.AddOccasionCollection")
          }
          description={t("Labels.OccasionCollectionDescription")}
        />

        <LocaleFormSwitcher
          locale={activeLocale}
          onChange={(locale) => {
            changeLocale(locale);
            clearErrors();
          }}
        />

        <div
          className={cn(`flex-1 overflow-auto px-4 pb-6 pt-2`, {
            "font-cairo": isArabic,
            "font-inter": !isArabic,
          })}
          dir={dir}
        >
          <form
            ref={form}
            onSubmit={(e) => {
              void handleSubmit(onSubmit)(e);
            }}
            className="space-y-4 relative"
          >
            <SingleFormImageUploader
              control={control}
              name="banner"
              label={tLive("Fields.Banner")}
            />

            <Card>
              <CardContent className="flex items-center gap-2">
                <div className="bg-[#f4c2c233] p-2.5 rounded-lg">
                  <Flower2 className="size-5 text-[#b88686]" />
                </div>
                <div>
                  <p className="font-semibold text-sm">
                    {watchName?.[activeLocale] || tLive("Placeholders.Name")}
                  </p>
                  <p className="text-muted-foreground text-xs mt-1">
                    /{watchSlug || tLive("Placeholders.Name")}
                  </p>
                </div>
              </CardContent>
            </Card>

            <SectionLabel>{tLive("Labels.Details")}</SectionLabel>
            {availableLocales.map((lang) => (
              <Input<OccasionFormValues>
                key={lang}
                label={tLive("Fields.Name")}
                placeholder={tLive("Placeholders.Name")}
                name={`name.${lang}` as const}
                type="text"
                className={`${activeLocale === lang ? "" : "hidden"}`}
                register={register}
                errors={errors}
                required
              />
            ))}

            <Input<OccasionFormValues>
              label={tLive("Fields.Slug")}
              placeholder={tLive("Placeholders.Slug")}
              name="slug"
              type="text"
              register={register}
              errors={errors}
              required
              prefix="/"
              description={tLive("Labels.SlugHint")}
            />

            {availableLocales.map((locale) => (
              <div
                key={locale}
                className={cn({
                  hidden: activeLocale !== locale,
                })}
              >
                <NormalFormRichText<OccasionFormValues>
                  key={activeLocale}
                  control={control}
                  label={tLive("Fields.Description")}
                  name={`description.${locale}`}
                  placeholder={tLive("Placeholders.Description")}
                />
              </div>
            ))}

            <Separator className="bg-border" />
            <SectionLabel>{tLive("Labels.PromotionalDateRange")}</SectionLabel>
            <div className="space-y-3">
              <p className="text-xs text-muted-foreground">
                {tLive("Labels.PromotionalDateRangeDescription")}
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input<OccasionFormValues>
                  name="starts_at"
                  register={register}
                  label={tLive("Fields.StartDate")}
                  type="date"
                  errors={errors}
                />

                <Input<OccasionFormValues>
                  name="ends_at"
                  register={register}
                  label={tLive("Fields.EndDate")}
                  type="date"
                  errors={errors}
                />
              </div>
            </div>

            <Separator className="bg-border" />
            <SectionLabel>{tLive("Labels.Color")}</SectionLabel>
            <div className="space-y-3">
              <p className="text-xs text-muted-foreground">
                {tLive("Labels.ColorDescription")}
              </p>
              <Controller
                name="color"
                control={control}
                render={({ field }) => {
                  const selectedColors = field.value ?? "";

                  return (
                    <div className="space-y-1.5">
                      <div className="flex flex-wrap gap-2">
                        {getListOfColors(occasion?.color || watchColor).map(
                          (color) => {
                            const isSelected = selectedColors === color;

                            return (
                              <Button
                                key={color}
                                type="button"
                                variant="outline"
                                className={cn(
                                  "h-8 w-8 rounded-full border border-border",
                                  {
                                    "border-2 border-primary": isSelected,
                                  },
                                )}
                                style={{ backgroundColor: color }}
                                onClick={() => {
                                  const nextColors = isSelected ? "" : color;
                                  field.onChange(nextColors);
                                }}
                              >
                                {isSelected && <Check />}
                              </Button>
                            );
                          },
                        )}

                        <div className="relative h-8 w-8">
                          <Button
                            variant="outline"
                            className="w-8 h-8 rounded-full border-2 border-dashed bg-white cursor-pointer"
                          ></Button>
                          <input
                            type="color"
                            className="absolute inset-0 h-full w-full cursor-pointer opacity-0"
                            onChange={(event) => {
                              field.onChange(event.target.value);
                            }}
                          />
                        </div>
                      </div>

                      <FieldError errors={[errors.color]} />
                    </div>
                  );
                }}
              />
            </div>

            <Separator className="bg-border" />
            <SectionLabel>{tLive("Labels.Visibility")}</SectionLabel>
            <Switch<OccasionFormValues>
              name="is_visible"
              control={control}
              label={tLive("Labels.VisibilityLabel")}
              description={tLive("Labels.VisibilityDescription")}
            />
          </form>
        </div>
        <Footer form={form} loading={isSubmitting} />
      </SheetContent>
    </Sheet>
  );
}
