"use client";

import {
  Occasion,
  occasionCollectionSchema,
  OccasionFormValues,
} from "@/types/occasions";
import { toast } from "sonner";
import Input from "../form/input";
import Footer from "../form/footer";
import Header from "../form/header";
import Switch from "../form/switch";
import { Button } from "../ui/button";
import { Flower2 } from "lucide-react";
import { useEffect, useRef } from "react";
import AddButton from "../form/add-button";
import { Separator } from "../ui/separator";
import { cn, createSlug } from "@/lib/utils";
import { useRouter } from "@/i18n/navigation";
import { Card, CardContent } from "../ui/card";
import SectionLabel from "../form/section-label";
import NormalFormRichText from "../form/rich-text";
import { postOccasionAction } from "@/lib/occasion";
import { zodResolver } from "@hookform/resolvers/zod";
import { availableLocales } from "@/constants/shared";
import { useLocale, useTranslations } from "next-intl";
import { useFormLocale } from "@/hooks/use-form-locale";
import LocaleFormSwitcher from "../reusable/locale-form-switcher";
import { SubmitHandler, useForm, useWatch } from "react-hook-form";
import SingleFormImageUploader from "../form/single-image-uploader";
import { Sheet, SheetClose, SheetContent, SheetTrigger } from "../ui/sheet";

// Get default values for the form based on the occasion collection data
function getDefaultValues(sortOrder: number, occasion?: Occasion) {
  return {
    name: occasion?.name_translations || { en: "", ar: "" },
    description: occasion?.description_translations || { en: "", ar: "" },
    slug: occasion?.slug || "",
    is_visible: occasion?.is_visible ?? true,
    type: occasion?.type || "bouquet",
    sort_order: occasion?.sort_order || sortOrder || 0,
    banner: occasion?.banner_url || "",
    starts_at: occasion?.starts_at?.split("T")[0] || "",
    ends_at: occasion?.ends_at?.split("T")[0] || "",
  };
}

export default function CreateEdit({
  occasion,
  trigger,
  totalOccasionItems,
}: {
  occasion?: Occasion;
  trigger?: React.ReactNode;
  totalOccasionItems: number;
}) {
  const router = useRouter();
  const locale = useLocale();
  const t = useTranslations("Occasions");
  const tCommon = useTranslations("Common");
  const form = useRef<HTMLFormElement>(null);
  const closeBtn = useRef<HTMLButtonElement>(null);
  const isSlugManuallyEdited = useRef(Boolean(occasion?.slug));
  const lastAutoGeneratedSlug = useRef(occasion?.slug || "");
  const { tLive, changeLocale, activeLocale, dir, isArabic } =
    useFormLocale("Occasions");

  const {
    control,
    register,
    reset,
    setValue,
    setError,
    getValues,
    trigger: triggerValidation,
    handleSubmit,
    formState: { errors, isSubmitting, isSubmitted },
  } = useForm<OccasionFormValues>({
    defaultValues: getDefaultValues(totalOccasionItems, occasion),
    resolver: zodResolver(
      occasionCollectionSchema((key) => tLive(key as never)),
    ),
  });

  useEffect(() => {
    if (isSubmitted) {
      void triggerValidation();
    }
  }, [triggerValidation, isSubmitted, activeLocale]);

  // Watch the color, name, and slug fields for changes
  const watchName = useWatch({ control, name: "name" });
  const watchSlug = useWatch({ control, name: "slug" });

  // Effect to automatically generate slug based on the name field when it changes, unless the slug has been manually edited
  useEffect(() => {
    if (isSlugManuallyEdited.current) return;

    const sourceName = watchName?.en?.trim() || "";
    const generatedSlug = createSlug(sourceName);
    lastAutoGeneratedSlug.current = generatedSlug;

    if (generatedSlug === getValues("slug")) return;

    setValue("slug", generatedSlug, {
      shouldDirty: Boolean(generatedSlug),
      shouldValidate: true,
    });
  }, [activeLocale, getValues, setValue, watchName]);

  // Effect to detect if the slug has been manually edited by the user
  useEffect(() => {
    if (
      !isSlugManuallyEdited.current &&
      typeof watchSlug === "string" &&
      watchSlug !== lastAutoGeneratedSlug.current
    ) {
      isSlugManuallyEdited.current = true;
    }
  }, [watchSlug]);

  const onSubmit: SubmitHandler<OccasionFormValues> = async (data) => {
    const failedMessage = occasion
      ? tCommon("UpdateFailed")
      : tCommon("CreationFailed");

    let result: Awaited<ReturnType<typeof postOccasionAction>>;

    try {
      result = await postOccasionAction(data, occasion?.id);
    } catch (error) {
      // The request itself failed (offline, upload too large for the server)
      console.error("Error submitting occasion:", error);
      toast.error(failedMessage);
      return;
    }

    if (result.success) {
      toast.success(result.message);
      router.refresh();
      closeBtn.current?.click();
      return;
    }

    if (result.errors) {
      Object.entries(result.errors).forEach(([field, message]) => {
        toast.error(message);
        setError(field as keyof OccasionFormValues, {
          type: "server",
          message,
        });
      });

      return;
    }

    toast.error(result.message ?? failedMessage);
  };

  return (
    <Sheet
      onOpenChange={(open) => {
        if (!open) return;

        // Start from the latest saved values every time the sheet opens
        isSlugManuallyEdited.current = Boolean(occasion?.slug);
        lastAutoGeneratedSlug.current = occasion?.slug || "";
        reset(getDefaultValues(totalOccasionItems, occasion));
      }}
    >
      {trigger ? (
        <SheetTrigger asChild>{trigger}</SheetTrigger>
      ) : (
        <AddButton label={t("Labels.AddOccasionCollection")} />
      )}

      <SheetContent
        showCloseButton={false}
        className="flex h-full flex-col sm:max-w-2xl"
        side={locale === "ar" ? "left" : "right"}
      >
        <SheetClose asChild>
          <Button ref={closeBtn} className="hidden"></Button>
        </SheetClose>

        <Header
          title={
            occasion
              ? t("Labels.EditOccasionCollection")
              : t("Labels.AddOccasionCollection")
          }
          description={t("Labels.OccasionCollectionDescription")}
        />

        <LocaleFormSwitcher
          locale={activeLocale}
          onChange={(locale) => {
            changeLocale(locale);
          }}
        />

        <div
          className={cn(`flex-1 overflow-auto px-4 pb-6 pt-2`, {
            "font-cairo": isArabic,
            "font-inter": !isArabic,
          })}
          dir={dir}
        >
          <form
            ref={form}
            onSubmit={(e) => {
              if (isSubmitting) {
                e.preventDefault();
                return;
              }

              void handleSubmit(onSubmit, (errors) => {
                // Check if current locale is English and there are Arabic field errors
                if (activeLocale === "en") {
                  const hasArErrors = errors.name?.ar || errors.description?.ar;
                  if (hasArErrors) {
                    changeLocale("ar");
                    return;
                  }
                }

                // Check if current locale is Arabic and there are English field errors
                if (activeLocale === "ar") {
                  const hasEnErrors = errors.name?.en || errors.description?.en;
                  if (hasEnErrors) {
                    changeLocale("en");
                    return;
                  }
                }
              })(e);
            }}
            className="space-y-4 relative"
          >
            <SingleFormImageUploader
              control={control}
              name="banner"
              label={tLive("Fields.Banner")}
            />

            <Card>
              <CardContent className="flex items-center gap-2">
                <div className="bg-[#f4c2c233] p-2.5 rounded-lg">
                  <Flower2 className="size-5 text-[#b88686]" />
                </div>
                <div>
                  <p className="font-semibold text-sm">
                    {watchName?.[activeLocale] || tLive("Placeholders.Name")}
                  </p>
                  <p className="text-muted-foreground text-xs mt-1">
                    /{watchSlug || tLive("Placeholders.Name")}
                  </p>
                </div>
              </CardContent>
            </Card>

            <SectionLabel>{tLive("Labels.Details")}</SectionLabel>
            {availableLocales.map((lang) => (
              <Input<OccasionFormValues>
                key={lang}
                label={tLive("Fields.Name")}
                placeholder={tLive("Placeholders.Name")}
                name={`name.${lang}` as const}
                type="text"
                className={`${activeLocale === lang ? "" : "hidden"}`}
                register={register}
                errors={errors}
                required
              />
            ))}

            <Input<OccasionFormValues>
              label={tLive("Fields.Slug")}
              placeholder={tLive("Placeholders.Slug")}
              name="slug"
              type="text"
              register={register}
              errors={errors}
              required
              prefix="/"
              description={tLive("Labels.SlugHint")}
            />

            {availableLocales.map((locale) => (
              <div
                key={locale}
                className={cn({
                  hidden: activeLocale !== locale,
                })}
              >
                <NormalFormRichText<OccasionFormValues>
                  key={activeLocale}
                  control={control}
                  label={tLive("Fields.Description")}
                  name={`description.${locale}`}
                  placeholder={tLive("Placeholders.Description")}
                />
              </div>
            ))}

            <Separator className="bg-border" />
            <SectionLabel>{tLive("Labels.PromotionalDateRange")}</SectionLabel>
            <div className="space-y-3">
              <p className="text-xs text-muted-foreground">
                {tLive("Labels.PromotionalDateRangeDescription")}
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input<OccasionFormValues>
                  name="starts_at"
                  register={register}
                  label={tLive("Fields.StartDate")}
                  type="date"
                  errors={errors}
                />

                <Input<OccasionFormValues>
                  name="ends_at"
                  register={register}
                  label={tLive("Fields.EndDate")}
                  type="date"
                  errors={errors}
                />
              </div>
            </div>

            <Separator className="bg-border" />
            <SectionLabel>{tLive("Labels.Visibility")}</SectionLabel>
            <Switch<OccasionFormValues>
              name="is_visible"
              control={control}
              label={tLive("Labels.VisibilityLabel")}
              description={tLive("Labels.VisibilityDescription")}
            />
          </form>
        </div>
        <Footer form={form} loading={isSubmitting} />
      </SheetContent>
    </Sheet>
  );
}
