import type { Metadata } from "next";
import { Inter, Playfair_Display, Tajawal, Cairo } from "next/font/google";
import "@/assets/css/globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { DirectionProvider } from "@/components/ui/direction";
import { Toaster } from "@/components/ui/sonner";

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const TajawalFont = Tajawal({
  variable: "--font-tajawal",
  subsets: ["arabic"],
  weight: ["400", "500", "700", "200"],
});

const PlayfairDisplayFont = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const CairoFont = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
  weight: ["400", "500", "700", "200"],
});

export const metadata: Metadata = {
  title: {
    default: "Blúme Petals",
    template: "Blúme Petals - %s",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }

  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html
      lang={locale}
      dir={dir}
      className={`${InterFont.variable} ${TajawalFont.variable} ${CairoFont.variable} ${PlayfairDisplayFont.variable} h-full antialiased`}
    >
      <NextIntlClientProvider>
        <DirectionProvider dir={dir}>
          <body className="min-h-full flex flex-col">
            {children}
            <Toaster />
          </body>
        </DirectionProvider>
      </NextIntlClientProvider>
    </html>
  );
}
